---
bibliography: references.bib
---

# Research fields, disciplines, and topics

## Introduction

Research is not a monolith, and what we might want to call the global research community is in fact divided into several communities and sub-communities who operate as more or less independent fields, in the Bourdieusian sense. Terms like "field", "research area", "domain", "disciplines", "specialties", "subject categories" are more or less synonymous and refer to categories of knowledge. In this chapter, we will use the term "discipline" to refer to such groups, and we will discuss their importance for bibliometrics, and the challenges associated with delineating them and identifying what discipline(s) an entity (e.g., publication, researcher, journal) belongs to.

::: callout-note
## What are disciplines

The following quote highlights a few key points about disciplines and what defines them:

> "*Disciplines are defined (in part) and recognized by the academic **journals** in which research is published, and the **learned societies** and **academic departments or faculties** within colleges and universities to which their practitioners belong*" ([Wikipedia](https://en.wikipedia.org/wiki/Academic_discipline))
:::

## Classification (the noun)

A classification is essentially a list of categories in which entities can be classified (what disciplines exist). Many classifications have been developed by organizations around the world, and the best classification to use is often determined by availability as well as the subject and goals of the analysis. Below are a few examples of general classifications (that cover all disciplines) and disciplinary classifications (that cover single disciplines with a higher level of granularity than the general classifications).

### General classifications

-   The **Science Metrix classification** **of research outputs** categorizes scientific journals and articles in 5 domains, 20 fields and 174 subfields. The classification can be downloaded [here](https://science-metrix.com/classification/).

-   The **Scopus All Science Journal Classification (ASJC)** divides journals in 334 fields and 4 research areas. The list of ASJC fields can be found [here](https://service.elsevier.com/app/answers/detail/a_id/15181/supporthub/scopus/).

-   The **National Science Foundation** (**NSF) classification** is a tried and tested mutually exclusive classification used in the Science & Engineering Indicators since the 1970s. It was originally designed by CHI Research [@archambault2011]. It contains three layers: 2 domains, 14 fields, and 143 specialties.

-   The **Web of Science Subject Categories** is a journal-level non-exclusive classification of journals in 250 subject categories available in the Web of Science. More information can be found [here](https://images.webofknowledge.com/images/help/WOS/hp_subject_category_terms_tasca.html).

-   The **Field of Science and Technology (FOS) classification of the** **OECD** has 40 FOS grouped in six broad fields. Details can be found [here](https://www.oecd.org/science/inno/38235147.pdf). The Web of Science provides a mapping of the FOS and the Web of Science subject categories [here](http://help.prod-incites.com/inCites2Live/filterValuesGroup/researchAreaSchema/oecdCategoryScheme.html).

-   The **fields of research (FOR) from the** **Australian and New Zealand Standard Research Classification (ANZSRC)**. The FOR have three levels: divisions, groups, and fields. You can find more details on the [ANZSRC website](https://www.abs.gov.au/statistics/classifications/australian-and-new-zealand-standard-research-classification-anzsrc/latest-release). This classification is used by the Dimensions database to assign FOR to articles and to calculate the field citation ratio (FCR), which we will discuss again in chapter 7.

### Disciplinary classifications

Some disciplines have developed their own classification. Here are some examples.

-   **The** **Medical Subject Headings (MeSH)** are used in PubMed and Medline databases to facilitate searching (details [here](https://en.wikipedia.org/wiki/Medical_Subject_Headings)).

-   **The** **Mathematics Subject Classification (MSC)** (details [here](https://zbmath.org/static/msc2020.pdf)).

-   **The** **Journal of Economics Literature (JEL) classification in economics** (details [here](https://www.aeaweb.org/econlit/jelCodes.php?view=jel))

### Computational (bottom up) approaches

There exists a variety of computational approaches to divide any set of entities into groups that can (both do not always) make sense. Topic models are an example. That said, topic models are not that popular in bibliometric studies, for which researchers tend to adopt citation-based networks approaches (discussed in more details below).

## Classification (the verb)

Assigning one or multiple discipline to documents or other entities can be a challenging task. Depending on the objective of your analysis, it may be preferable to use the classification already available in the database you are using (or to choose a database that uses the classification that best suits your needs).

But how do we assign a discipline to another entity, like a researcher?

-   Do we use the discipline of their PhD?

-   Do we use the discipline of their current department or faculty?

-   Do we use the discipline classification of their articles or the journals in which they are published?

There is no right answer to these questions. Most often our main guide will be data availability and quality. The discipline of the Ph.D., for instance, is an information rarely available other than on the CV of the researcher. Furthermore, not all bibliographic records include the department of the authors, and when they do, they do not usually use controlled vocabulary so the same departments can come up with different names or spelling, and sometimes it will require some web searching to figure out the discipline to which the department could be assigned to. Moreover, the department names might not match your disciplinary classification which can make the pairing of departments with disciplines challenging. If the publications in our database are assigned to one or many disciplines, we can infer the discipline of the researcher using the papers they published, or the journals in which they published. What do we do when a researcher has 5 publications in Physics, 3 in chemistry and 4 in economics? Is that person a Physicist, a Chemist, an Economist? A mix?

## Describing disciplines

How can we represent disciplines (topics of interest, journals, researchers) using bibliometrics? The "simple" answer is that we can describe a discipline by looking at the entities that we put into that box. For example, to describe the field of management , we can look at the articles or journals that were assigned to the *management* discipline through some classification mechanism. Then we can look at different entities associated with these articles such as terms used in the articles (as a proxy for topics), journals, researchers, institutions, and countries to describe what the discipline is about, what are its main journals, and who are the agents involved in it. This can be done in two main ways: **rankings** and **networks.**

### Rankings

Bibliometric data is usually asymmetrically distributed so that:

-   A minority of researchers publish the majority of papers (Lotka's law)

-   A minority of journals publish the majority of works on a subject (Bradford's law)

-   A minority of words used account for the majority of occurrences (Zipf's law)

-   A minority of articles (of a researcher, a journal, a discipline, etc.) account for the majority of the citations in the whole [@larivière2016a].

Because of this, disciplines or other areas of research are sometimes described by identifying the most frequent keywords, journals, authors, and institutions. Because these types of analyses are easily done with the Web version of databases like Web of Science and Scopus, they are very popular among scholars outside of the bibliometrics field who often use the ranking methods to provide an empirical account of the main topics and actors involved in their area of expertise. These descriptions are however very limited and are ideally used with complementary approaches such as networks.

::: callout-note
## Note

Listing most frequent words used in titles and abstracts of articles published in a field without any other processing will not produce a meaningful representation of the topics of interest in a field given the presence of stop words (a, the, it, when, if) and other generic terms (research, data, results, analysis, etc.). So, it is important to filter out those words so the top words included in a table can adequately reflect the core topics of the discipline one is trying to describe.

**What is a topic?**

Topic and terms are not equivalent, and a topic is usually represented by a set of terms. For instance, the COVID-19 pandemic topic could be represented by terms like coronavirus, COVID, COVID-19, Omicron, etc. This is something to keep in mind as you dive into the data and try to determine what topics are or interest within a discipline or any set of publications.
:::

### Disciplines as networks

The structure of a discipline can be represented as a network of agents and research objects that are connected with one another to some degree. Different kinds of networks are typically used in bibliometrics:

#### **Co-occurrence networks**

Co-occurrence networks are undirected networks in which the edges are determined by the appearance of two entities in a set. Typical types of co-occurence networks include:

-   **Term co-occurrence networks** are constructed by considering in how many articles two terms appear together (co-occur). For example, if an article's title, abstract or keywords contains the terms "COVID-19" and "vaccine", then the terms "COVID-19" and "Vaccines" are linked.

-   **Bibliographic coupling networks**. Bibliographic coupling occurs when two articles contain a reference to the same article. For example, if article B and C both cite article A, then B and C are linked.

-   **Co-citation networks**. A co-citation between two articles occurs when they are both cited together in another article. For example, if article B and C are cited by articles A, then B and C are related. One of the issues with co-citations is that they take time to accumulate, so networks of recent articles are less accurate since the citations have yet form links between the articles.

#### Direct citation network

Direct citation networks are the most common for of **directed** networks that one will come across in bibliometrics. In a directed network, the relationship between two nodes has a direction: So when article A cites article B, a direct citation link from article A to article B is created. This is not the same as a direct citation link between article B and article A. In fact, it is extremely unlikely for A to cite B AND for B to cite A. Indeed, articles usually cite other articles that have already been published, which means that the cited articles can not cite the citing articles back.

### Networks in practice

If you completed the Data Management course (INFO6540) you might remember that a network has two core components: nodes and edges (also called vertices, or links).

#### Nodes

Node lists are typically comma- or tab-delimited files with a minimum of two columns:

-   **Id**. A unique identifier for the node

-   **Label**. A label for the node.

You can add as many columns as you wish with information about the nodes that you can use in your network visualization to adjust the color and size of the nodes or their labels. In fact, the label column is also not mandatory, and you could, in principle, have a nodes list with only an id column.

| Id  | Label     | Citations | Discipline          | any other column |
|-----|-----------|-----------|---------------------|------------------|
| 1   | Article A | 13        | Chemistry           | ...              |
| 2   | Article B | 5         | Physics             | ...              |
| 3   | Article C | 3         | Information Science | ...              |

: Example of a nodes list.

#### Edges

In an edge list, you will typically have a source node, a target node, the strength of their relationship and whether that relationship is directed or undirected. Note that when the network is undirected, it does not matter what nodes are entered in the source column and which ones are in the target column. However, you want to have each combinations of nodes be unique. For example, in the example edge list below, you would not want to include a row with node 2 as a target and node 1 as a source, because that edge is already captured in the first row.

| Source | Target | Weight | Type       |
|--------|--------|--------|------------|
| 1      | 2      | 4      | undirected |
| 1      | 3      | 2      | undirected |
| 2      | 3      | 1      | undirected |

: Example of an edges list

The **weight** column contains a numerical value that represents the strength of the link between the nodes. If we are building a co-citation network, then the weight would be the number of articles that cite both the source node and the target node. The edges list above thus indicates that article A and article B have been cited together 4 times, article A and article B 2 times, and article B and article C 1 time. This would suggest that article A and article B are more closely related to each other than to article C.

#### Visualizing the networks

-   **VOSviewer** is a free software developed by Nees Jan van Eck and Ludo Waltman of the Centre for Science and Technology Studies (CWTS) of Leiden University. The [website](https://www.vosviewer.com/) includes a lot of useful information to get you started.

-   **Gephi** is an open-source network visualization and analysis software. It offers more features and flexibility than VOSviewer, at the price of a slightly steeper learning curve. You can download Gephi [here](https://gephi.org/).

## References
