# Course overview {.unnumbered}

This book is a work-in-progress intended to support the course INFO6850 - Bibliometrics and Scholarly Communication offered at the School of Information Management, Dalhousie University.

The course introduces students to the scholarly communication system and the use of bibliometrics to measure the production, dissemination and use of knowledge. Topics covered will include the reward system of science, peer-review, scholarly publishing and open access, research funding, research evaluation, bibliometric and altmetric data sources and indicators, and networks.

## Learning outcomes

Upon completion of the course you will be able to:

1.  Explain the scholarly communication process.
2.  Select appropriate data sources to conduct a bibliometric study.
3.  Calculate and interpret bibliometric indicators.
4.  Visualize and analyze bibliometric networks.
5.  Use bibliometrics to support research evaluation processes.
6.  Explain the advantages and limitations of bibliometrics.
7.  Understand the social and organizational context of research evaluation

## Schedule

| Week | Section                           | Topic                                                                  |
|:----:|-----------------------------------|------------------------------------------------------------------------|
|  1   | Understanding the research system | Introduction: bibliometrics and scholarly communications               |
|  2   | Understanding the research system | Function, social structure, norms, and the research reward system.     |
|  3   | Understanding the research system | Journals, peer-review, and the organization and evaluation of research |
|  4   | Analyzing and evaluating research | Bibliometric data sources                                              |
|  5   | Analyzing and evaluating research | Delineating fields, disciplines, and topics                            |
|  6   | Analyzing and evaluating research | Measuring research outputs (authorship)                                |
|  7   | Analyzing and evaluating research | Measuring research impact (citations)                                  |
|  8   | Analyzing and evaluating research | Measuring media and policy attention to research (altmetrics)          |
|  9   | Analyzing and evaluating research | Visualizing research networks                                          |
|  10  | Improving the research system     | Open Research                                                          |
|  11  | Improving the research system     | Bias, errors, fraud, misconduct, and questionable research practices   |
|  12  | Improving the research system     | Equity, diversity, and inclusion in research                           |

## Assignments

| \#  | Assignment                                          | Value | Due date |
|:---:|-----------------------------------------------------|:-----:|:--------:|
|  1  | Article review                                      |  15%  |  Oct 3   |
|  2  | Outline of a bibliometric research project          |  5%   |  Oct 28  |
|  3  | Descriptive analysis of a research network          |  10%  |  Nov 18  |
|  4  | Research assessment report                          |  30%  |  Dec 2   |
|  5  | Research project                                    |  30%  |  Dec 16  |
| N/A | Engagement (preparation, attendance, participation) |  10%  |   N/A    |

::: callout-important
Use the course Brightspace to:

\- Access the detailed instruction for the assignments.

\- Submit your assignments.
:::

## Other information and resources

-   Use APA style for your references in all assignments.

-   Use [Zotero](www.zotero.org) (or another reference manager of your choice) to store your references and to cite them in your work. (not mandatory, but highly recommended).

-   You can use this [Word template](files/assignment-template.dotx) to write your assignments (not mandatory). Whether you use this template or not, use Word styles to format and structure your document.

-   Have fun.
